### ISSUE TITLE
Can it be compiled with msvc12(VS2013)?

### ISSUE THREAD

**Issue by jaejunlee0538** [mherb/kalman#11]
I got many errors with msvc12.
Many errors were related with template parameters. 
I guess the problem is c++11 support in msvc12.
Any body did compile with msvc12?

**Comment by mherb** [comment]
MSVC12 lacks a lot of very basic C++11 features (such as constexpr, see https://msdn.microsoft.com/en-us/library/hh567368.aspx) and is therefore not supported and will never be supported as the integration of more advanced C++11/14/17 features is planned for the near future. Please try to move to a more recent version of MSVC.
