### ISSUE TITLE
SquareRootUnscentedKalmanFilter.hpp   line 161  should be comment?

### ISSUE THREAD

**Issue by zy041984** [mherb/kalman#17]
Hi Markus, I have a small question.

In SquareRootUnscentedKalmanFilter.hpp function update(), whether function computeSigmaPoints() should be called here?
According to the paper, there's no need to compute x(k|k-1) here.
![image](https://user-images.githubusercontent.com/34560116/34024114-80a644dc-e183-11e7-950d-999f248bc28b.png)

**Comment by mherb** [comment]
Well spotted, thank you for pointing this out! I just pushed a quick-fix on master and will add a regressen test for that on develop.
